// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqME1xvTX1G1EMJXezbhtQJMM7zYEsRyQ',
    appId: '1:1052319698753:android:1fa5315188e5f3a1871bc0',
    messagingSenderId: '1052319698753',
    projectId: 'flutter-with-firebase-f7909',
    storageBucket: 'flutter-with-firebase-f7909.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHj19Uu1Kh6IBuFwZVt-fnugeSSUcQ4xE',
    appId: '1:1052319698753:ios:564709f7ac47d827871bc0',
    messagingSenderId: '1052319698753',
    projectId: 'flutter-with-firebase-f7909',
    storageBucket: 'flutter-with-firebase-f7909.firebasestorage.app',
    iosBundleId: 'com.example.study',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHj19Uu1Kh6IBuFwZVt-fnugeSSUcQ4xE',
    appId: '1:1052319698753:ios:564709f7ac47d827871bc0',
    messagingSenderId: '1052319698753',
    projectId: 'flutter-with-firebase-f7909',
    storageBucket: 'flutter-with-firebase-f7909.firebasestorage.app',
    iosBundleId: 'com.example.study',
  );
}
